### ISSUE TITLE
Paul Wouters Zone boundary implications

### ISSUE THREAD

**Issue by upros** [upros/acme-subdomains#45]
### Zone bondary implications
```
   the ACME client need only fulfill an
   ownership challenge against an ancestor domain identifier.
```

This document seems to have a "Public Suffix List" issue and no Security
Considerations to cover this. PSL is mentioned in RFC 8555, but limited to
the context of wildcards.

The draft hints at the server being able to allow or not allow subdomain
issuance but provides little guidance.  I think at minimum, advise should be
given not to allow issuance where it crosses a label that is present in
the Public Suffix List (PSL). Additionally, it could say this should not
be allowed for the root one or TLD zones, and that care should be taken
with Empty Non Terminals (ENS), eg "co.uk".

Currently, for a TLD to obtain a rogue certificate, it has to take over
a child zone by issuing new NS records or issue a (DNSSEC signed) A or
AAAA record directly into the child domain abusively crossing the zone cut.
These are auditable or rejectable as these DNSSEC keys are not used fo
subdomains in normal deployment. With this document, they just need to
issue a TXT record into their own zone, which is indistinguishable from
a normal operation of a DNSSEC zone key signing its own zone content.

So I believe some security guidance here would be useful.

**Comment by mcr** [comment]
Section 10.5.  CA Policy Considerations of RFC8555 lists the Public Suffix List, as a second consideration after wildcard, not depending upon wildcards.

>   o  For domain names:
>
>     *  If the leftmost label is a '*', then have the appropriate
>         checks been applied?
>
>      *  Is the name on the Public Suffix List?

**Comment by mcr** [comment]
(Public Suffix List appears only once in RFC8555, and it does not seem to have a reference!)
