### ISSUE TITLE
HTTP validation is forbidden for subdomains

### ISSUE THREAD

**Issue by FGasper** [upros/acme-subdomains#55]
CA Baseline requirements now forbid use of HTTP validation in issuance of subdomain certificates. This document in its current state seems to suggest the contrary in several places, e.g.:

https://github.com/upros/acme-subdomains/blob/07792f3965538ab5afc621510dc8b27884cc5178/draft-ietf-acme-subdomains.md?plain=1#L155

https://github.com/upros/acme-subdomains/blob/07792f3965538ab5afc621510dc8b27884cc5178/draft-ietf-acme-subdomains.md?plain=1#L199-L209

https://github.com/upros/acme-subdomains/blob/07792f3965538ab5afc621510dc8b27884cc5178/draft-ietf-acme-subdomains.md?plain=1#L640

**Comment by upros** [comment]
Hi @FGasper  the intent of this draft, just like ACME RFC 8555, is that it is not specific to public WebPKI where CA/B applies.

I'll point you to existing text in https://datatracker.ietf.org/doc/html/draft-ietf-acme-subdomains-07#section-7.3

"The ACME for Subdomains and the ACME specifications do not mandate
   any specific ACME server or CA policies, or any specific use cases
   for issuance of certificates.  For example, an ACME server could be
   used:

   *  to issue Web PKI certificates where the ACME server must comply
      with CA/Browser Forum [[CAB](https://datatracker.ietf.org/doc/html/draft-ietf-acme-subdomains-07#ref-CAB)] Baseline Requirements.

   *  as a Private CA for issuance of certificates within an
      organization.  The organization could enforce whatever policies
      they desire on the ACME server."

So conformance with CA/B is not mandatory.
